services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: php
    volumes:
      - type: bind
        source: ./
        target: /app
    user: dev
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: "serverName=cli" # Used by PhpStorm for path mapping
      COMPOSER_AUTH: "{\"github-oauth\": {\"github.com\":\"${GITHUB_TOKEN}\"}}"
    extra_hosts:
      - host.docker.internal:host-gateway
